name: threat_lens
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  provider: ^6.1.2

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0

  # Settings
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/avatars/ 

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter-regular.ttf
        - asset: assets/fonts/inter-light.ttf
          weight: 300
        - asset: assets/fonts/inter-medium.ttf
          weight: 500
        - asset: assets/fonts/inter-bold.ttf
          weight: 700
